# Generated by Django 5.1 on 2024-08-26 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=255)),
                ('Job_Title', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('passions', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Intermediate', 'Intermediate'), ('Experienced', 'Experienced')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.CharField(max_length=255)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cv_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='ProfileApp.cvdetails')),
            ],
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='cv_details', to='ProfileApp.language'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('cv_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='ProfileApp.cvdetails')),
            ],
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='skills',
            field=models.ManyToManyField(related_name='CVDETAILS', to='ProfileApp.skills'),
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_details', to='ProfileApp.userprofile'),
        ),
    ]
