# Generated by Django 5.1 on 2024-08-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdetails',
            name='role',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
